export const Toggle_Check_Box = 'Toggle_Check_Box'
export const Add_To_Do_Item = 'ActionType.Add_To_Do_Item'
export const Delete_To_Do_Item = 'ActionType.Delete_To_Do_Item'
export const Filter_Tab_All = 'Filter_Tab_All'
export const Filter_Tab_Completed = 'Filter_Tab_Completed'
export const Filter_Tab_InComplete = 'Filter_Tab_InComplete'
export const Edit_To_Do_Item = 'Edit_To_Do_Item'